### ISSUE TITLE
Problems executing setup.py

### ISSUE THREAD

**Issue by basit-7** [vislearn/dsacstar#11]
Hi, I made environment in conda with all the packages that you mentioned with correct versions, but I am constantly getting this error while running setup.py. 

dsacstar/dsacstar/dsacstar_util.h:193:5: error: ‘SOLVEPNP_P3P’ is not a member of ‘cv’

I am using OpenCV 3.4.2 and I manually set the paths for header and library files for for OpenCV in setup.py.

**Comment by ebrach** [comment]
That sounds like the compiler is still using a different version of OpenCV. I never encountered this. On which platform are you trying to compile?

**Comment by basit-7** [comment]
I am using Ubuntu 16.04. I set up the environment in Conda and installed OpenCV 3.4.2, also doubled checked to see if the version was different but it was 3.4.2. 

Below is the complete error. It would be great if you could help figure out the problem.

`[1/1] c++ -MMD -MF /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/build/temp.linux-x86_64-3.7/dsacstar.o.d -pthread -B /home/etri/miniconda3/envs/dsac_star/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/etri/miniconda3/envs/dsac_star/include/opencv -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include/TH -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include/THC -I/home/etri/miniconda3/envs/dsac_star/include/python3.7m -c -c /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar.cpp -o /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/build/temp.linux-x86_64-3.7/dsacstar.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=dsacstar -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/build/temp.linux-x86_64-3.7/dsacstar.o 
c++ -MMD -MF /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/build/temp.linux-x86_64-3.7/dsacstar.o.d -pthread -B /home/etri/miniconda3/envs/dsac_star/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/etri/miniconda3/envs/dsac_star/include/opencv -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include/TH -I/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/include/THC -I/home/etri/miniconda3/envs/dsac_star/include/python3.7m -c -c /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar.cpp -o /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/build/temp.linux-x86_64-3.7/dsacstar.o -fopenmp -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=dsacstar -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar.cpp:42:0:
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_util.h: In function ‘void dsacstar::sampleHypotheses(dsacstar::coord_t&, const cv::Mat_<cv::Point_<int> >&, const cv::Mat_<float>&, int, unsigned int, float, std::vector<std::pair<cv::Mat, cv::Mat> >&, std::vector<std::vector<cv::Point_<int> > >&, std::vector<std::vector<cv::Point_<float> > >&, std::vector<std::vector<cv::Point3_<float> > >&)’:
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_util.h:193:5: error: ‘SOLVEPNP_P3P’ is not a member of ‘cv’
     cv::SOLVEPNP_P3P))
     ^
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_util.h: In function ‘void dsacstar::refineHyp(dsacstar::coord_t&, const cv::Mat_<float>&, const cv::Mat_<cv::Point_<int> >&, const cv::Mat_<float>&, float, unsigned int, float, dsacstar::pose_t&, cv::Mat_<int>&)’:
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_util.h:579:6: error: ‘SOLVEPNP_ITERATIVE’ is not a member of ‘cv’
      cv::SOLVEPNP_ITERATIVE : 
      ^
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_util.h:580:6: error: ‘SOLVEPNP_P3P’ is not a member of ‘cv’
      cv::SOLVEPNP_P3P))
      ^
In file included from /media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar.cpp:45:0:
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_derivative.h: In function ‘cv::Mat_<double> dsacstar::dPNP(const std::vector<cv::Point_<float> >&, std::vector<cv::Point3_<float> >, const cv::Mat&, float)’:
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_derivative.h:138:45: error: ‘SOLVEPNP_P3P’ is not a member of ‘cv’
      int pnpMethod = (imgPts.size() == 4) ? cv::SOLVEPNP_P3P : cv::SOLVEPNP_ITERATIVE;
                                             ^
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_derivative.h:138:64: error: ‘SOLVEPNP_ITERATIVE’ is not a member of ‘cv’
      int pnpMethod = (imgPts.size() == 4) ? cv::SOLVEPNP_P3P : cv::SOLVEPNP_ITERATIVE;
                                                                ^
/media/etri/ETRI/basit_ETRI/dsacstar/dsacstar/dsacstar_derivative.h:141:45: error: ‘SOLVEPNP_P3P’ is not a member of ‘cv’
      int effectiveObjPoints = (pnpMethod == cv::SOLVEPNP_P3P) ? 3 : objPts.size();
                                             ^
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1515, in _run_ninja_build
    env=env)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 42, in <module>
    cmdclass={'build_ext': BuildExtension})
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/etri/miniconda3/envs/dsac_star/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension
`

**Comment by arefmiri** [comment]
I have the same problem running the setup.py and get exactly the same error. Could you fix the problem?

**Comment by basit-7** [comment]
@arefmiri Unfortunately, I was not able to fix tis problem.

**Comment by ebrach** [comment]
As I said before, this error indicates that your compiler still uses a different OpenCV version than the one required by the code. You might have installed the correct version in Conda but I assume there is a different version, potentially installed system-wide, that has priority for the compiler. 

I would suggest to investigate the system variables etc that the compiler uses to determine which library version to rely on.

**Comment by ebrach** [comment]
You could also try to adjust the code to align with the OpenCV that your compile uses, eg. changing uses of "cv::SOLVEPNP_P3P" to whatever namespace that enum is in for your installed version of OpenCV. This investigation might also tell you which version of OpenCV the compiler is actually using.
